### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by ALMER789** [Punit9464/Avon#1]
/node_modules/discord-hybrid-sharding/dist/Structures/Data.js:8
> throw new Error('NO CHILD/MASTER EXISTS OR SUPPLIED CLUSTER_MANAGER_MODE IS INCORRECT');

**Comment by Punit9464** [comment]
Your Issue is clearly invalid because there is no use of the discord-hybrid-sharding in the source codes.Provided it uses sharding manager of discord.js.

So it's completely irrelevant asking your queries this way.

Contact me at: https://discord.gg/avonbot 
If u want your queries to be solved.

Thank you!
